### ISSUE TITLE
Overflow check for addition of two EncodedNumbers

### ISSUE THREAD

**Issue by mpnd** [n1analytics/javallier#11]
The current implementation of addition of two `EncodedNumber`s in `PaillierContext` does not check overflow.

**Comment by wilko77** [comment]
Should it check that? After all, it lives in modular arithmetic land. Then you would have to do the same for the other operations with only encoded numbers (e.g. multiplication, subtraction).

On a more general basis, I don't understand why we have arithmetic on encoded numbers. I can't see a use case for encoding numbers under a PaillierContext, and then not encrypting them.
