### ISSUE TITLE
Limit the range of valid exponents in Number

### ISSUE THREAD

**Issue by mpnd** [n1analytics/javallier#7]
This is to prevent memory blow up.

**Comment by wilko77** [comment]
I don't understand this issue. Exponents are represented by `int`. That's always the same amount of memory. Limiting the range of `int` won't change anything.

**Comment by mpnd** [comment]
The main reason to limit the range of valid exponents is to prevent the significand from getting too large.

While `Number` class has been removed in 84b894a2a7eb447ffd6da967fa507b47ca9319b5, could this still be relevant for `EncodedNumber`?
