### ISSUE TITLE
Optimise subtraction operation

### ISSUE THREAD

**Issue by mpnd** [n1analytics/javallier#9]
At the moment, `a - b` is computed by adding `a` and the additive inverse of `b`. Is there a way to optimise the calculation (i.e., without computing the additive inverse of `b`)?

**Comment by wilko77** [comment]
Not in the encrypted space. Paillier only supports addition.
In the unencrypted space there certainly are ways without computing the additive inverse, however, the computation of the additive inverse in the unencrypted space is very cheap. Is there a performance issue?
